In [ ]:
### sql server (3 tables Silver ) ---> sql server (1 one Big table Gold) )

In [10]:
import pandas as pd

In [8]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://DESKTOP-2A0QBS7\SQLEXPRESS/project1_DWH"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
    "&TrustServerCertificate=yes"
)

In [11]:
df_customers = pd.read_sql("SELECT * FROM Silver.customers",con=engine)
df_orders = pd.read_sql("SELECT * FROM Silver.orders",con=engine)
df_products = pd.read_sql("SELECT * FROM Silver.products",con=engine)

c:\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

In [12]:
df_customers

    customer_id       full_name                      email        city
0             1       Ahmed Ali            ahmed@gmail.com       Cairo
1             2  Mohamed Hassan          mohamed@gmail.com        Giza
2             3    Omar Mahmoud             omar@gmail.com  Alexandria
3             4    Sara Ibrahim     sara.ibrahim@gmail.com       Luxor
4             5   Youssef Nabil    youssef.nabil@yahoo.com       Aswan
5             6       Mona Adel        mona.adel@gmail.com    Mansoura
6             7    Khaled Samir   khaled.samir@outlook.com       Tanta
7             8    Nour Elsayed     nour.elsayed@gmail.com        Suez
8             9     Hana Yasser      hana.yasser@gmail.com    Ismailia
9            10     Karim Fouad      karim.fouad@gmail.com       Cairo
10           11     Laila Kamal      laila.kamal@yahoo.com   Port Said
11           12  Mostafa Rashad   mostafa.rashad@gmail.com      Fayoum
12           13      Dina Hatem       dina.hatem@gmail.com     Zagazig
13           14        Amr Zaki       amr.zaki@hotmail.com       Minya
14           15      Rana Fathy       rana.fathy@gmail.com        Qena
15           16     Tarek Saleh      tarek.saleh@gmail.com       Sohag
16           17   Mariam Ashraf    mariam.ashraf@gmail.com   Beni Suef
17           18    Hassan Gamal     hassan.gamal@yahoo.com    Damietta
18           19      Salma Wael       salma.wael@gmail.com        Giza
19           20   Bassel Sherif  bassel.sherif@outlook.com       Cairo
20           21    Farida Kamal     farida.kamal@gmail.com  Alexandria
21           22   Mahmoud Ezzat    mahmoud.ezzat@yahoo.com       Luxor
22           23      Reem Hosny       reem.hosny@gmail.com       Aswan
23           24      Ziad Fouad     ziad.fouad@hotmail.com    Mansoura
24           25       Nada Adel        nada.adel@gmail.com       Tanta
25           26    Sherif Nabil   sherif.nabil@outlook.com        Suez
26           27      Yara Samir       yara.samir@gmail.com    Ismailia
27           28     Ali Mostafa      ali.mostafa@yahoo.com   Port Said
28           29     Heba Rashad      heba.rashad@gmail.com      Fayoum
29           30    Kareem Hatem     kareem.hatem@gmail.com     Zagazig
30           31      Ghada Zaki     ghada.zaki@hotmail.com       Minya
31           32      Adel Fathy       adel.fathy@gmail.com        Qena
32           33     Menna Saleh      menna.saleh@gmail.com       Sohag
33           34     Ramy Ashraf      ramy.ashraf@yahoo.com   Beni Suef
34           35     Esraa Gamal      esraa.gamal@gmail.com    Damietta
35           36      Walid Wael     walid.wael@outlook.com        Giza
36           37    Rania Sherif     rania.sherif@gmail.com       Cairo
37           38     Tamer Kamal      tamer.kamal@yahoo.com  Alexandria
38           39      Doaa Ezzat       doaa.ezzat@gmail.com       Luxor
39           40      Ehab Hosny     ehab.hosny@hotmail.com       Aswan
40           41   Shaimaa Fouad    shaimaa.fouad@gmail.com    Mansoura
41           42      Hazem Adel     hazem.adel@outlook.com       Tanta
42           43   Nourhan Nabil    nourhan.nabil@gmail.com        Suez
43           44     Islam Samir      islam.samir@yahoo.com    Ismailia
44           45     Aya Mostafa      aya.mostafa@gmail.com   Port Said
45           46    Basma Rashad     basma.rashad@gmail.com      Fayoum
46           47     Maged Hatem    maged.hatem@hotmail.com     Zagazig
47           48    Passant Zaki     passant.zaki@gmail.com       Minya
48           49      Fady Fathy       fady.fathy@yahoo.com        Qena
49           50    Habiba Saleh     habiba.saleh@gmail.com       Sohag

In [13]:
df_orders

    order_id  customer_id  product_id  quantity  order_date
0       1001            1         101         1  2026-09-01
1       1002            2         102         2  2026-09-02
2       1003            1         103         1  2026-09-03
3       1004            3         104         3  2026-09-04
4       1005            4         105         2  2026-09-05
5       1006            5         106         1  2026-09-06
6       1007            6         107         4  2026-09-07
7       1008            7         108         1  2026-09-08
8       1009            8         109         2  2026-09-09
9       1010            9         110         3  2026-09-10
10      1011           10         101         1  2026-09-11
11      1012           11         102         2  2026-09-12
12      1013           12         103         5  2026-09-13
13      1014           13         104         1  2026-09-14
14      1015           14         105         2  2026-09-15
15      1016           15         106         1  2026-09-16
16      1017           16         107         3  2026-09-17
17      1018           17         108         2  2026-09-18
18      1019           18         109         1  2026-09-19
19      1020           19         110         4  2026-09-20
20      1021           20         101         2  2026-09-21
21      1022           21         102         1  2026-09-22
22      1023           22         103         3  2026-09-23
23      1024           23         104         1  2026-09-24
24      1025           24         105         2  2026-09-25
25      1026           25         106         1  2026-09-26
26      1027           26         107         5  2026-09-27
27      1028           27         108         2  2026-09-28
28      1029           28         109         1  2026-09-29
29      1030           29         110         3  2026-09-30

In [14]:
df_products

   product_id       product_name     category      brand   price
0         101          iPhone 15  Electronics      Apple  799.99
1         102         Galaxy S24  Electronics    Samsung  699.99
2         103       Nike Air Max        Shoes       Nike  129.99
3         104          Air Fryer         Home    Philips  149.99
4         105     Wireless Mouse  Electronics   Logitech   25.50
5         106       Office Chair    Furniture       IKEA  199.00
6         107     Running Shorts     Clothing     Adidas   19.99
7         108       Coffee Maker         Home  Nespresso  129.00
8         109     Leather Wallet  Accessories      Gucci  199.00
9         110  Bluetooth Speaker  Electronics        JBL   89.99

In [19]:
df_output = pd.merge(df_orders, df_customers, how='inner', on='customer_id')
df_output = pd.merge(df_output, df_products, how='inner', on='product_id')
df_output.head(5)

,order_id,customer_id,product_id,quantity,order_date,full_name,email,city,product_name,category,brand,price
0,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo,iPhone 15,Electronics,Apple,799.99
1,1002,2,102,2,2026-09-02,Mohamed Hassan,mohamed@gmail.com,Giza,Galaxy S24,Electronics,Samsung,699.99
2,1003,1,103,1,2026-09-03,Ahmed Ali,ahmed@gmail.com,Cairo,Nike Air Max,Shoes,Nike,129.99
3,1004,3,104,3,2026-09-04,Omar Mahmoud,omar@gmail.com,Alexandria,Air Fryer,Home,Philips,149.99
4,1005,4,105,2,2026-09-05,Sara Ibrahim,sara.ibrahim@gmail.com,Luxor,Wireless Mouse,Electronics,Logitech,25.50

In [20]:
df_output.head(5)

,order_id,customer_id,product_id,quantity,order_date,full_name,email,city,product_name,category,brand,price
0,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo,iPhone 15,Electronics,Apple,799.99
1,1002,2,102,2,2026-09-02,Mohamed Hassan,mohamed@gmail.com,Giza,Galaxy S24,Electronics,Samsung,699.99
2,1003,1,103,1,2026-09-03,Ahmed Ali,ahmed@gmail.com,Cairo,Nike Air Max,Shoes,Nike,129.99
3,1004,3,104,3,2026-09-04,Omar Mahmoud,omar@gmail.com,Alexandria,Air Fryer,Home,Philips,149.99
4,1005,4,105,2,2026-09-05,Sara Ibrahim,sara.ibrahim@gmail.com,Luxor,Wireless Mouse,Electronics,Logitech,25.50

In [22]:
df_output ['total_amount'] = df_output ['quantity'] * df_output ['price']
df_output.head(5)

,order_id,customer_id,product_id,quantity,order_date,full_name,email,city,product_name,category,brand,price,total_amount
0,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo,iPhone 15,Electronics,Apple,799.99,799.99
1,1002,2,102,2,2026-09-02,Mohamed Hassan,mohamed@gmail.com,Giza,Galaxy S24,Electronics,Samsung,699.99,1399.98
2,1003,1,103,1,2026-09-03,Ahmed Ali,ahmed@gmail.com,Cairo,Nike Air Max,Shoes,Nike,129.99,129.99
3,1004,3,104,3,2026-09-04,Omar Mahmoud,omar@gmail.com,Alexandria,Air Fryer,Home,Philips,149.99,449.97
4,1005,4,105,2,2026-09-05,Sara Ibrahim,sara.ibrahim@gmail.com,Luxor,Wireless Mouse,Electronics,Logitech,25.50,51.00

In [23]:
df_output.to_sql(
    'fact', 
    con=engine,
    schema='gold',
    if_exists='append', 
    index=False
    )

30